{
 "title": "TradeAgent Monitor",
 "description": "TradeAgent",
 "tags": [ "trade_agent" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "  ", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Today Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total FROM trade_balance WHERE date_part('year',trade_day) = date_part('year',now()) AND date_part('month',trade_day) = date_part('month',now()) AND date_part('day',trade_day) = date_part('day',now());"
    }
   ]
  },
  {
   "title": "Total Balance(since 2022-03-24)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(total) from trade_balance;"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[1m])*100/8)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100*sum(container_memory_usage_bytes{name!=\"\"})/sum(machine_memory_bytes)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"trade_agent|sinopac_mq_srv|trade_agent_mqtt|redis\"}[1m]))/1024",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"trade_agent|sinopac_mq_srv|trade_agent_mqtt|redis\"}[1m]))/1024",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Runtime Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container_name=~\"trade_agent|sinopac_mq_srv|trade_agent_mqtt|redis\"}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"trade_agent|sinopac_mq_srv|trade_agent_mqtt|redis\"}[1m])*100/8) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mib" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"trade_agent|sinopac_mq_srv|trade_agent_mqtt|redis\"}/1024/1024) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}