{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    },
    { "expr": "time" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(container_memory_usage_bytes{image!=\"\"}))/(sum(machine_memory_bytes))"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{container_name=~\"sinopac_srv|toc_trader\"}",
     "maxLines": 300
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}