{
 "title": "ToC Machine Trading Monitor",
 "description": "ToC Machine Trading",
 "tags": [ "TMT" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]))*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-100*(node_memory_MemAvailable_bytes{job=\"trader-exporter\"}/node_memory_MemTotal_bytes{job=\"trader-exporter\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"toc-machine-trading\"}[$__rate_interval])",
     "legendFormat": "{{ job }}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"toc-sinopac-python\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"toc-fugle-python\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{container_name=~\"toc-machine-trading|toc-sinopac-python|toc-fugle-python\"}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"toc-machine-trading\"}/1024/1024",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"toc-sinopac-python\"}/1024/1024",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"toc-fugle-python\"}/1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "MQ Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_published_total{job=\"toc-rabbitmq\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}